gitsearch/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^git-search-home/', include('search.urls',namespace='search')),
]

search/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home , name='home'),
    url(r'^error/$', views.error , name='error'),
    url(r'^(?P<username>\w+)$', views.results , name='results'),
]

search/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

search/forms.py
from django import forms

class SearchForm(forms.Form):
	username = forms.CharField(max_length=100)
	

search/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from .forms import SearchForm
import json
import requests
# Create your views here.

url = 'https://api.github.com/users/'

def home(request):
	if request.method == 'POST':
		form = SearchForm(request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			user_url = url + username
			user_info_r = requests.get(user_url)
			print(username)
			print(user_info_r.status_code)
			if user_info_r.status_code != 200:
				error_url = reverse('search:error')
				return HttpResponseRedirect(error_url)
			results_url = reverse('search:results', kwargs={'username':username})
			print(results_url)
			return HttpResponseRedirect(results_url)
	else:
		form = SearchForm()

	context = {'form':form}
	return render(request, 'search.html', context)
	
def error(request):
	return render(request, 'error.html')


def results(request, username):
	print("helloo")
	user_url = url + username
	user_info_r = requests.get(user_url)
	user_info = get_repos(user_info_r)
	repo_no = len(user_info)
	context = {'user_info':user_info, 'repo_no':repo_no}
	return render(request, 'results.html', context)


def get_repos(user_info_r):
	user_info = json.loads(user_info_r.text)
	repos_url = user_info['repos_url']
	repo_info_r = requests.get(repos_url)
	repo_info = json.loads(repo_info_r.text)
	print("Number of repositories --> " + str(len(repo_info)))
	print(repo_info)
	repo_count = 0
	repo_list = []
	for repo in repo_info:
		repo_dict = {}
		repo_name = (repo['name'])
		repo_id = repo['id']
		repo_dict["id"] = repo_id
		repo_dict["name"] = repo_name 
		print("Repository name is " + repo_name)
		branch_list = get_branches(repo)
		commit_list = get_commits(repo)
		repo_dict['commits'] = commit_list
		repo_dict['branches'] = branch_list
		repo_list.append(repo_dict)
		print("\n")
	return repo_list

def get_branches(repo_json):
	repo_name = repo_json['name']
	branches_url = repo_json['branches_url']
	branch_info_r = requests.get(branches_url[:-9])
	branch_info = json.loads(branch_info_r.text)
	print("Number of branches --> " + str(len(branch_info)))
	branch_count = 1
	branch_list = []
	for branch in branch_info:
		branch_dict = {}
		branch_dict['name'] = branch['name']
		branch_list.append(branch_dict)
	return branch_list

def get_commits(repo_json):
	commits_url = repo_json['commits_url']
	commit_info_r = requests.get(commits_url[:-6])
	commit_info = json.loads(commit_info_r.text)
	print("Number of commits --> " + str(len(commit_info)))
	commit_count = 1
	commit_list = []
	for commit in commit_info:
		commit_dict = {}
		commit_dict['message'] = commit['commit']['message']
		commit_list.append(commit_dict)
	return commit_list

search/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
</head>
<body>
<h3>The username is not valid. Please enter a valid username</h3>
<a href="{% url 'search:home' %}">Click here to search again.</a>


</body>
</html>

search/templates/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
</head>
<body>
	

<div>
	<ul>
	<h3>Number of repositories is {{ repo_no }}</h3>
	{% for repo in user_info %}
	<br/><br/>
		<li>Repository Name --> {{ repo.name }} </li>
		<li>Repository id --> {{ repo.id }} </li>
		<p>Here are the branches of this repository</p>
		<ul>
		{% for branch in repo.branches %}
			<li>Branch Name --> {{ branch.name }}</li>			
		{% endfor %}
		</ul>
		<p>Here are the commits made to this repository</p>
		<ol>
		{% for commit in repo.commits %}
			<li>Commit Name --> {{ commit.message }}</li>
		{% endfor %}
		</ol>
		{% endfor %}
	</ul>
</div>
<a href="{% url 'search:home' %}">Click here to search for another user</a>
</body>
</html>

search/templates/search.html
    
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
</head>
<body>
	<div>
        <form method='POST'> {% csrf_token %}
            {{ form.as_p }}
            <input type='Submit' value='Search'>
        </form>
    </div>

</body>
</html>